services:
  backend:
    build:
      context: ./minecraft-backend
    ports:
      - "8000:8000"
    volumes:
      - ./minecraft-backend:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./minecraft-frontend
    ports:
      - "3000:5173"
    volumes:
      - ./minecraft-frontend:/app
